spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_sharing
    username: postgres
    password: per4atka
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true